-- Create the users table (accounts). Scope: Create Account (sc-39).
--
-- Design notes:
--  * id: UUID generated by PostgreSQL (gen_random_uuid), avoids leaking row
--    counts / enabling guessable enumeration.
--  * email: stored lowercase-canonical; unique constraint backs the
--    application-layer uniqueness guard (belt and suspenders).
--  * password_hash: stores only the Argon2id hash — never a plaintext password.
--  * role: the six MVP roles; sign-up always defaults to 'USER'.
CREATE TABLE users (
    id            UUID         NOT NULL DEFAULT gen_random_uuid(),
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(32)  NOT NULL DEFAULT 'USER',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN (
        'USER',
        'RESTAURANT_OWNER',
        'VERIFIED_RESTAURANT_OWNER',
        'VERIFICATION_COMMITTEE',
        'ISSUES_COMMITTEE',
        'EXTENSION_TRIGGER'
    ))
);