-- Create the restaurant_listings table (unverified listings, listing-first model).
-- Scope: Add Listing backend foundation (sc-138).
--
-- Design notes:
--  * id: UUID generated by PostgreSQL (gen_random_uuid), matching users/refresh_tokens
--    — avoids leaking row counts / enabling guessable enumeration.
--  * location: PostGIS geography(Point, 4326) — the geospatial column the search
--    vertical will filter/order with ST_DWithin + ST_DistanceSphere. The extension
--    is enabled idempotently so this migration is self-contained on a fresh DB.
--  * owner_id: FK to users(id) with the default NO ACTION — an owner with listings
--    cannot be silently deleted (data integrity before convenience).
--  * verification_status: listing-first model — every listing starts 'UNVERIFIED';
--    only reachable value today. 'VERIFIED' becomes legal once owner-claim +
--    certificate verification lands (sc-139+), at which point the CHECK grows.
--  * cutting_method: hand-cut / machine-cut / unspecified ("any" filter value).
--  * cuisine: free-form validated string (no ratified taxonomy yet) — see
--    domain/restaurant/Cuisine.kt.
--
-- Open founder flags (docs/reviews/sc-138-external-services.md §5), noted not
-- decided: ODbL share-alike on OSM/Photon-derived fields; dedupe thresholds.
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE restaurant_listings (
    id                 UUID        NOT NULL DEFAULT gen_random_uuid(),
    name               VARCHAR(255) NOT NULL,
    address            VARCHAR(512) NOT NULL,
    location           geography(Point, 4326) NOT NULL,
    cuisine            VARCHAR(64)  NOT NULL,
    cutting_method     VARCHAR(32)  NOT NULL,
    owner_id           UUID        NOT NULL,
    verification_status VARCHAR(32) NOT NULL DEFAULT 'UNVERIFIED',
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_restaurant_listings PRIMARY KEY (id),
    CONSTRAINT fk_restaurant_listings_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT ck_restaurant_listings_cutting_method CHECK (cutting_method IN (
        'HAND_CUT',
        'MACHINE_CUT',
        'UNSPECIFIED'
    )),
    CONSTRAINT ck_restaurant_listings_verification_status CHECK (verification_status IN (
        'UNVERIFIED'
    ))
);

-- Owner-scoped lookups (e.g. "my listings").
CREATE INDEX idx_restaurant_listings_owner ON restaurant_listings (owner_id);
-- Spatial lookup for the search vertical (distance filter/ordering).
CREATE INDEX idx_restaurant_listings_location ON restaurant_listings USING GIST (location);
