-- Seed verified halal restaurants (sc-155).
-- GENERATED from seed_restaurants_geocoded.json by scripts/generate_seed_migration.py
-- (last generated against seed_restaurants_geocoded.json, 30 locations / 28 brands).
-- Do NOT hand-edit; regenerate, then bump to the next migration version.
--
-- Source: OpenStreetMap via Photon (photon.komoot.io), ODbL 1.0; coordinates WGS84.
-- Every row starts UNVERIFIED with provenance 'research-seed / photon-geocode'
-- (listing-first model), cuisine NULL, cutting_method UNSPECIFIED, owner_id NULL.
-- Brand vs location: one brand row per distinct name; The Halal Guys is 1 brand, 3 locations.
-- Idempotent: brands ON CONFLICT (name); listings ON CONFLICT (normalised location,
-- scoped to seed provenance) DO NOTHING — dedupe by geocoded-normalised location, not raw name.

-- Brands (one per distinct name).
INSERT INTO brands (name) VALUES ('Osmow''s') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Paramount Fine Foods') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('The Halal Guys') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Iqbal Foods') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Karahi Point') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Lazeez Shawarma') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Aroma Fine Indian Cuisine') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Sultan of Samosas') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Bamiyan Kabob') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Watan Kabob') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Madina Naan & Kabob') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Sami''s Kabab House') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Ayat') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Tanoreen') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Bedouin Tent') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Mamoun''s Falafel') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('The Kati Roll Company') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Yemen Cafe') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Punjabi Deli') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Kabab King') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Dera') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Al-Amir Lebanese Restaurant & Club') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Afrah') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Andalous Mediterranean Buffet') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Ali Baba Mediterranean') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Halal Bros') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Halal Wings') ON CONFLICT (name) DO NOTHING;
INSERT INTO brands (name) VALUES ('Caspian Grill') ON CONFLICT (name) DO NOTHING;

-- Listings (locations keyed by geolocation; brand resolved by name).
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Osmow''s', '505 St. Clair Ave W', ST_SetSRID(ST_MakePoint(-79.418493, 43.682921), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Osmow''s'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Paramount Fine Foods', 'The Queensway', ST_SetSRID(ST_MakePoint(-79.542104, 43.617063), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Paramount Fine Foods'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'The Halal Guys', '563 Yonge St', ST_SetSRID(ST_MakePoint(-79.384523, 43.665206), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'The Halal Guys'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Iqbal Foods', 'Birchmount Rd', ST_SetSRID(ST_MakePoint(-79.269949, 43.707410), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Iqbal Foods'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Karahi Point', 'Overlea Blvd', ST_SetSRID(ST_MakePoint(-79.344214, 43.707742), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Karahi Point'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Lazeez Shawarma', 'Rogers Rd', ST_SetSRID(ST_MakePoint(-79.470950, 43.681855), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Lazeez Shawarma'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Aroma Fine Indian Cuisine', '287 King St W', ST_SetSRID(ST_MakePoint(-79.389767, 43.646238), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Aroma Fine Indian Cuisine'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Sultan of Samosas', '1677 O''Connor Dr', ST_SetSRID(ST_MakePoint(-79.304067, 43.718833), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Sultan of Samosas'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Bamiyan Kabob', '62 Overlea Blvd', ST_SetSRID(ST_MakePoint(-79.343431, 43.707949), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Bamiyan Kabob'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Watan Kabob', '6974 Financial Dr', ST_SetSRID(ST_MakePoint(-79.751092, 43.609900), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Watan Kabob'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Madina Naan & Kabob', 'Overlea Blvd', ST_SetSRID(ST_MakePoint(-79.349801, 43.704492), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Madina Naan & Kabob'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'The Halal Guys', '307 E 14th St', ST_SetSRID(ST_MakePoint(-73.984423, 40.732288), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'The Halal Guys'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Sami''s Kabab House', '35-57 Crescent St', ST_SetSRID(ST_MakePoint(-73.933112, 40.758313), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Sami''s Kabab House'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Ayat', 'Hull Ave', ST_SetSRID(ST_MakePoint(-74.098708, 40.580655), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Ayat'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Tanoreen', '7523 3rd Ave', ST_SetSRID(ST_MakePoint(-74.027888, 40.630815), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Tanoreen'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Bedouin Tent', '405 Atlantic Ave', ST_SetSRID(ST_MakePoint(-73.984465, 40.686966), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Bedouin Tent'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Mamoun''s Falafel', '30 St Marks Pl', ST_SetSRID(ST_MakePoint(-73.988505, 40.728801), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Mamoun''s Falafel'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'The Kati Roll Company', '99 MacDougal St', ST_SetSRID(ST_MakePoint(-74.001091, 40.729656), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'The Kati Roll Company'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Yemen Cafe', '176 Atlantic Ave', ST_SetSRID(ST_MakePoint(-73.993663, 40.689878), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Yemen Cafe'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Punjabi Deli', '114 E 1st St', ST_SetSRID(ST_MakePoint(-73.986706, 40.722647), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Punjabi Deli'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Kabab King', '73-01 37th Rd', ST_SetSRID(ST_MakePoint(-73.892270, 40.747267), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Kabab King'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Dera', '72-09 Broadway', ST_SetSRID(ST_MakePoint(-73.893450, 40.747705), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Dera'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'The Halal Guys', '5444 Lemmon Ave', ST_SetSRID(ST_MakePoint(-96.823657, 32.828011), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'The Halal Guys'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Al-Amir Lebanese Restaurant & Club', '3885 Belt Line Rd', ST_SetSRID(ST_MakePoint(-96.849844, 32.953530), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Al-Amir Lebanese Restaurant & Club'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Afrah', 'E Main St', ST_SetSRID(ST_MakePoint(-96.728031, 32.948070), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Afrah'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Andalous Mediterranean Buffet', '1601 N Central Expwy', ST_SetSRID(ST_MakePoint(-96.720983, 32.969601), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Andalous Mediterranean Buffet'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Ali Baba Mediterranean', '2103 N Central Expwy', ST_SetSRID(ST_MakePoint(-96.715556, 32.978694), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Ali Baba Mediterranean'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Halal Bros', '11521 N FM 620', ST_SetSRID(ST_MakePoint(-97.827540, 30.452930), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Halal Bros'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Halal Wings', '1200 Barbara Jordan Blvd', ST_SetSRID(ST_MakePoint(-97.707527, 30.306530), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Halal Wings'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;
INSERT INTO restaurant_listings (name, address, location, cuisine, cutting_method, owner_id, brand_id, provenance, verification_status) VALUES ( 'Caspian Grill', '12518 Research Blvd', ST_SetSRID(ST_MakePoint(-97.760465, 30.428596), 4326)::geography, NULL, 'UNSPECIFIED', NULL, (SELECT id FROM brands WHERE name = 'Caspian Grill'), 'research-seed / photon-geocode', 'UNVERIFIED') ON CONFLICT (location_lat_6, location_lng_6) WHERE provenance = 'research-seed / photon-geocode' DO NOTHING;

